### ISSUE TITLE
Also send api key in X-API-Key header

### ISSUE THREAD

**Issue by chasers** [supabase/realtime-js#108]
Send the api key in the header also.

Eventually need to deprecate the api key url param to keep api keys out of logs.

**Comment by w3b6x9** [comment]
@chasers This only works server-side (see: https://github.com/theturtle32/WebSocket-Node/issues/386#issuecomment-974414416). What should we do about client-side?

**Comment by abc3** [comment]
we can pass custom param through [protocols](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket)

```js
new WebSocket("ws://realtime_path", "API_KEY")
```

then get a result from header `Sec-WebSocket-Protocol: API_KEY`

**Comment by w3b6x9** [comment]
> we can pass custom param through [protocols](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket)
> 
> ```js
> new WebSocket("ws://realtime_path", "API_KEY")
> ```
> 
> then get a result from header `Sec-WebSocket-Protocol: API_KEY`

@abc3 i had a chance to investigate this and came to the conclusion that this wouldn't work b/c the user socket does not have access to the `Sec-WebSocket-Protocol` header.

we could create an endpoint in the server for client to make a request with their api key, send back a one time token, and have client send the token as query param. this way, only the one time token ends up in logs.
