### ISSUE TITLE
How to listen for updates and deletes SINCE given point in time?

### ISSUE THREAD

**Issue by pie6k** [supabase/realtime-js#114]
# Feature request

## Is your feature request related to a problem? Please describe.

Sometimes it is required to get all updates (aka perform sync) since given point in time.

Example might be offline cached copy of the data.

Let's say row A is created by client A and stored locally.

Then client A did not open the app for a week.

In the meanwhile, client B removed row A.

Then, client A opens the app again. How can we get information that row A was removed without having to request all existing rows and checking if row A is still there. (It might be impossible for large databases).

## Describe the solution you'd like

I'd like to subscribe for updates providing date when I last checked. I'd expect the client to give me array of all changes and then listening to ongoing changes normally.

## Describe alternatives you've considered

I built something similar in house in one project.

It was based on custom "sync-request" table that had info of all updates and removes and date when it happened.

Then client was fetching list of all sync requests since last check, and for every updated item was performing a check if still has access to given row. 

If it was not able to get her it, client assumes it was either removed or became not accessible due to some permissions, and removed it from local cache.

This approach has limitations, tho. For example you might lose access to row A due to change in row B (eg row A is "group" and row B is "group membership"). If group membership is changed to "blocked", group might no longer be accessed so requires a sync check.

Another alternative is adding "deletedAt" column and setting it instead of removing the row.

This way we can subscribe like "get all rows where updatedAt or deletedAt is greater than last check date"

This is simple and works, but has some limitations:

It is still not handling item becoming inaccessible due to changes in different item.

It might not be suitable in some cases due to privacy reasons where we want to hard-remove the row from database.

## Additional context

It might be called "Delta fetching". It is based on assumption that you never fetch the same row twice if it is not needed.

**Comment by w3b6x9** [comment]
@pie6k thanks for this feature request!

I don't think we'll be implementing this any time soon so it's best to create your own custom solution. Feel free to share it here though as I'm sure it'll server as inspiration.
