### ISSUE TITLE
Chore: update Github description to supabase.com

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/realtime-js#124]
# Chore

## Describe the chore

update Github description  from [supabase.io](https://supabase.com) to [supabase.com](https://supabase.com)

<img width="1392" alt="Screen Shot 2021-12-16 at 3 28 11 PM" src="https://user-images.githubusercontent.com/70828596/146444535-8d14c606-c732-4f33-80b1-12afcfc6befa.png">

**Comment by inian** [comment]
Done thanks @Isaiah-Hamilton
