### ISSUE TITLE
Realtime allows multiple subscriptions to table

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/realtime-js#127]
# Bug report
Documentations for realtime.js says:

> Duplicate Join Subscriptions
>  While the client may join any number of topics on any number of channels, the client may only hold a single subscription for each unique topic at any given time. When attempting to create a duplicate subscription, the server will close the existing channel, log a warning, and spawn a new channel for the topic. The client will have their channel.onClose callbacks fired for the existing channel, and the new channel join will have its receive hooks processed as _normal.
> 

Currently creating additional subscriptions to same table (or same table and exact filter) generate a new subscription.

## To Reproduce

create multiple subscriptions to the same table and filter

## Expected behavior
Based on the documentation, and I think the intent of the code, reusing a subscription should not create a new one.
I assumed it would so do not keep track of closing subscriptions when I renew.

This obviously can be handled by keeping track of subscriptions and closing them, but is a waste if realtime.js is supposed to handle it.
When dealing with connections going online and offline part of my code restarts subscriptions as part of a bigger block of code to reload the data being monitored in realtime as it state is no longer valid if connection goes offline.

## Screenshots

![realtime connections](https://user-images.githubusercontent.com/54564956/147840539-cc9e2883-3a02-415a-99ae-88b6e626a6fa.JPG)

![duplicate connections on socket](https://user-images.githubusercontent.com/54564956/147840541-ff5a4872-09e0-4297-b44a-7e8feead08cf.JPG)

## System information

supabase 1.29.1

**Comment by w3b6x9** [comment]
@GaryAustin1 thanks for reporting this! this is most likely a bug. i'm currently investigating.

**Comment by w3b6x9** [comment]
@GaryAustin1 can you please give this fix a try? https://github.com/supabase/realtime-js/pull/128

**Comment by GaryAustin1** [comment]
Thanks, I'll try it in the morning...
