### ISSUE TITLE
Realtime loses heartbeats (and data events) if multiple events occur during a 60 second window, each under 30 seconds apart.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/realtime-js#133]
# Bug report
It appears realtime.js resets its websocket heartbeat timer on realtime events
If realtime events come in over a minute period, each 30 seconds or less apart the websocket heartbeat does not go out in time and the connection closes and resets.  This can cause loss of data during the reconnect period.

## To Reproduce

Set up a table with two columns (id,count) and no RLS.  Use UI to add one row with id=1. Enable replication.
Have code running do an update of a column every 30 seconds or less. (30 is borderline, 29 or less yields no heartbeats).
Have another app/client subscribe to the table.  
In the network tab you will see multiple websockets over time, each because of heartbeat failure.

NOTE: There is no obvious error generated other than reconnects at the websocket level.  Subscribe status will indicate "SUBSCRIPTION_ERROR" but code will keep running.  Data can be silently lost during reconnect.

## Expected behavior

Realtime should handle reasonable bursts to the client over minutes.  A chat app can easily do several responses in that time period.

## Screenshots
30 second loop.  Note the missing update event that occurred during the reconnect.  Number of events to failure is random.

![log](https://user-images.githubusercontent.com/54564956/154756118-68afab5b-3d77-4226-8a57-5f5dec30ff8c.JPG)

![connect close](https://user-images.githubusercontent.com/54564956/154756165-49b04bd6-b3a3-4709-a4a9-15f2c847e160.JPG)

I'm guessing the problem occurs here in the Supabase RealtimeClient.js code:

![realtimecode](https://user-images.githubusercontent.com/54564956/154756414-5443ef41-7854-471f-a41d-5ecca56edcd7.JPG)

10 second loop.  Always 6 events then disconnect.
![10sec](https://user-images.githubusercontent.com/54564956/154756904-f3424ab0-d43a-4f20-80cf-9879fbff6382.JPG)

## System information
Current supabase.js (and 1.29.3)
Any browser any OS.

## Additional context
Code Sample:
![code](https://user-images.githubusercontent.com/54564956/154764165-1e39a3c7-1af7-4f96-be4f-dc12e0dae728.JPG)

![pollcode](https://user-images.githubusercontent.com/54564956/154756978-d358067d-e2a6-4ecc-97c8-af09604cf80b.JPG)

**Comment by w3b6x9** [comment]
possibly related: https://github.com/supabase/realtime-js/issues/94

**Comment by GaryAustin1** [comment]
Looks like this has been known awhile.  Not good.
If you reset heartbeat in that code on any websocket response (and I'm just guessing it does that as I looked for a heartbeat reset in your code based on what I was seeing) you are basically saying you can't have more than 1 event per client per minute, otherwise you are into "well if you have more than one, they can't be less than 30 seconds apart unless no more than events*seconds apart > 60s".   So if it is true you reset heartbeat that is not going to work.

**Comment by GaryAustin1** [comment]
@w3b6x9 at this point I almost believe you all need to not reconnect a dropped connection (based on this type of issue, plus internet connection, plus background tabs, plus mobile device power save modes).  All these events can cause a dropped connection, even if for 3 seconds.   You could lose data and not know it.

It needs to be made clear if you need RELIABLE realtime data you must reset everything after each socket disconnect (which are far more frequent than I suspected).  

This appears to be a known issue for other websocket users:
https://socket.io/docs/v4/troubleshooting-connection-issues/  suggests server "heartbeats" with socket.io 4
https://github.com/SignalR/SignalR/issues/4536   SignalR from Microsoft appears to have had to deal with this.

As an aside, this is what I'm looking at now on an android test, going to sleep for 30 minutes or so and then going back to it.  38 lost 1 minute events and a ton of time lost restarting realtime websockets for no reason.   Pretty clear realtime needs to be shut down as soon as device goes to sleep and totally restarted.  At least so far my quick look shows iOS just shutting down everything when closed (still lose data, but don't waste time doing it).

![image](https://user-images.githubusercontent.com/54564956/154785315-8e08fd38-8b0b-4bbe-b736-20361809af63.png)

**Comment by GaryAustin1** [comment]
@w3b6x9 The multiple requests withing 60 seconds killing heartbeat has been fixed with latest release of supabase.js.
Thanks

One issue is that is numbered release 0.0.0....
{
  "name": "@supabase/supabase-js",
  "version": "0.0.0",

instead of 1.30.4.

**Comment by w3b6x9** [comment]
@GaryAustin1 nice, glad it's fixed.

regarding the proper version number in `package.json`, we'll have to figure out the best way to do that and apply it to all supabase js client libs.

**Comment by darora** [comment]
The version is being correctly set in the released packages already. What's the use case requiring the repo to be updated?

```
> npm i @supabase/supabase-js

removed 443 packages, changed 6 packages, and audited 30 packages in 16s

found 0 vulnerabilities
> grep 'version' node_modules/@supabase/supabase-js/package.json 
  "version": "1.30.4",

> grep 'version' node_modules/@supabase/realtime-js/package.json 
  "version": "1.3.6",
```

**Comment by GaryAustin1** [comment]
For my test case I used the cdn version:
![image](https://user-images.githubusercontent.com/54564956/155047963-630e7563-ad62-4c3d-81f4-0c4aebcaae53.png)
which does contain the correct version files and I think has had correct version before, but don't use it a lot versus npm version for my real project.
In the github source I noticed the 0.0.0 still there.

In my real project with npm it reflects the real package number in package.json.

**Comment by darora** [comment]
@GaryAustin1 which CDN was that? We'll look into why that might be happening

**Comment by GaryAustin1** [comment]
I'm pretty sure both the documented ones as I switched to see if I was getting correct code.
https://cdn.jsdelivr.net/npm/@supabase/supabase-js is what I have in the test code now.

**Comment by darora** [comment]
Thanks @GaryAustin1 - I think https://github.com/supabase/supabase-js/pull/384 should fix this
