### ISSUE TITLE
RealtimeChannel.ts fails to import isEqual in Nuxt3+supabase-module environment.

### ISSUE THREAD

**Issue by y-migita** [supabase/realtime-js#148]
# Bug report

## Describe the bug

RealtimeChannel.ts fails to import isEqual in Nuxt3+supabase-module environment.

## To Reproduce

https://github.com/y-migita/supabase-nuxt3

1. Clone repo
2. run "yarn install"
3. run "yarn dev"

## Screenshots

<img width="894" alt="ScreenShot_20220402 2@2x" src="https://user-images.githubusercontent.com/95598040/161367006-9b932579-d035-4fdf-a331-07674d6f31c7.png">

## System information

- macOS
- Chrome 100.0.4896.60
- @supabase/realtime-js@^1.4.0
- nuxt3@latest 3.0.0-27480376.fdd38f9
- @nuxtjs/supabase ^0.1.4

**Comment by w3b6x9** [comment]
@y-migita please upgrade to `supabase-js` v1.33.3

**Comment by y-migita** [comment]
Thanks for the fix!

**Comment by w3b6x9** [comment]
@y-migita you got it!
