### ISSUE TITLE
Difference between realtime and realtime-js documentation ... token on connect

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/realtime-js#154]
# Bug report

In realtime documentation it shows:
```var channel = socket.channel('realtime:public:rls_table', { user_token: JWT })```
In realtime-js documentation it shows:
```var databaseChanges = client.channel('realtime:*')```
And there is no discussion of providing a user_token.

I don't use realtime-js directly, but if it requires the user_token then documentation should reflect that.

## Expected behavior

Documentation should reflect the correct way of doing things in both repositories.

**Comment by w3b6x9** [comment]
@GaryAustin1 Thanks! Will update `realtime-js` docs.

**Comment by GaryAustin1** [comment]
I was just working with a user in Discord getting deletes and not inserts/updates using realtime-js directly.   Went thru all the normal stuff, back and forth as looks like an RLS issue, finally suggested they contact support as out of ideas...  Then I dug deeper and found this, which they did not have.  Let them know, but they are offline now...  Not sure if that is their issue or not...

**Comment by w3b6x9** [comment]
@GaryAustin1 Thanks for helping said user. I'm currently debugging with the user and I think you may be right about the token.

**Comment by w3b6x9** [comment]
@GaryAustin1 That was an odd one. User created a new project and everything is fully working. There was nothing out of the ordinary so it was quite strange it wasn't working before. Anyways, appreciate you helping out the user!

**Comment by GaryAustin1** [comment]
Hate those... Need to be watching for something a user can do to grants/permissions or such.  realtime schema mainly has the subscription table which seems to go empty between connections and certainly server resets, which the user said they did.  That leaves migrations, but I assume you can see those.  I guess something strange could be going on with replications getting out of whack on tables...
