### ISSUE TITLE
WARN Require cycle

### ISSUE THREAD

**Issue by visoft** [supabase/realtime-js#160]
# Bug report

Using the latest supbase-js client, I receive a warning in my React Native application. I am not directly using realtime-js in my application at all.

## Describe the bug

```
WARN  Require cycle: node_modules/@supabase/realtime-js/dist/main/RealtimeSubscription.js -> node_modules/@supabase/realtime-js/dist/main/lib/push.js -> node_modules/@supabase/realtime-js/dist/main/RealtimeSubscription.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

## To Reproduce

I have the following code:

```
import { SUPABASE_URL, SUPABASE_KEY } from '@env';
import { createClient } from '@supabase/supabase-js';

export const supabaseClient = createClient(SUPABASE_URL, SUPABASE_KEY, {
  localStorage: AsyncStorage as any,
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: false,
});
```

When I use the `supabaseClient` the first time, I receive the warning.

## Expected behavior

No warning message from React Native

## Screenshot
![image](https://user-images.githubusercontent.com/208794/170485367-cdc7af01-c909-4247-9b96-017b158c0efb.png)

## System information

- OS: macOS
- Version of supabase-js: 1.35.3
- Version of Node.js: 16.14.2
- React Native: 0.68.2

**Comment by w3b6x9** [comment]
Related: https://github.com/supabase/realtime-js/issues/164

**Comment by w3b6x9** [comment]
@visoft this is resolved. please upgrade to [v1.7.4](https://github.com/supabase/realtime-js/releases/tag/v1.7.4).
