### ISSUE TITLE
500 error upon deployment of a Supabase subscription to Cloudflare Pages

### ISSUE THREAD

**Issue by craigdrayton** [supabase/realtime-js#165]
# Bug report

## Describe the bug
I have a SvelteKit app that uses the '@sveltejs/adapter-cloudflare' adapter to deploy to Cloudflare Pages.

The app uses the @supabase/supabase-js library to connect to my Supabase project. I've deployed an app with data reading & writing successfully to Supabase.

I've added a basic supabase subscription, and having deployed the change I get the following error on page load: 

> 500 Cannot assign to read only property 'stack' of object ''
> TypeError: Cannot assign to read only property 'stack' of object ''

The subscription works correctly in local development, but fails when deployed.

Here is the code snippet that causes the failure:

```
const steps = readable(null, (set) => {
        supabase
            .from('steps')
            .select('*')
            .order('created_at')
            .then(({error, data}) => set(data))

        /* Code above here deploys successfully. Code below does not. */

        const subscrption = supabase
            .from('steps')
            .on('*', (payload) => {
                if (payload.eventType === 'INSERT') {
                    set([...get(steps), payload.new])
                }
            })
            .subscribe()
        return () => supabase.removeSubscription(subscrption)
    })
```

## System information

- OS: Windows
- Browser (if applies): Chrome
- Version of supabase-js: 1.35.4
- Version of Node.js: 16

**Comment by craigdrayton** [comment]
Well color me confused, when I do nothing other than add a try/catch block around the subscription, the 500 error stops occurring, but also the subscription works!?

```
const steps = readable(null, (set) => {
        supabase
            .from('steps')
            .select('*')
            .order('created_at')
            .then(({error, data}) => set(data))

        try {
            const subscrption = supabase
            .from('steps')
            .on('INSERT', (payload) => {
                set([...get(steps), payload.new])
            })
            .subscribe()

            return () => supabase.removeSubscription(subscrption)
        } catch(e) {
            console.log(e)
        }
    })
```

**Comment by w3b6x9** [comment]
@craigdrayton oh interesting, I have never seen that before. Glad it’s working!

**Comment by w3b6x9** [comment]
@craigdrayton can you please share the error that was console logged? perhaps it can give us a clue as to what was causing the 500.

**Comment by craigdrayton** [comment]
That's what I mean is strange - no error was logged so it appears that the error did not occur because the try/catch block was there...

The original error message was:
>500 Cannot assign to read only property 'stack' of object ''

I actually suspect the root issue is somewhere in the SvelteKit cloudflare adapter, which assigns to a 'stack' property in the code it generates at `.svelte-kit\cloudflare\_worker.js`

**Comment by w3b6x9** [comment]
@craigdrayton gotcha, i'll close this issue for now but feel free to re-open if you're hunch regarding CF adapter doesn't work out.

**Comment by m3hari** [comment]
I end up here  debugging the nuxt3 app on Cloudflare pages, I keep getting this error

 `500 Class constructor EventEmitter cannot be invoked without 'new.` 

It happens whenever I use `supabase.channel`, which is because of this package. Thanks to @craigdrayton  🙏  , wrapping a real-time call with `try-catch` solves my issue.


Here is a full stack trace  of the error:

```
TypeError: Class constructor EventEmitter cannot be invoked without 'new'
    at new WebSocketClient$1 (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:26411:7)
    at new W3CWebSocket (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:26632:192)
    at Wd.default.connect (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:27285:31)
    at RealtimeChannel.subscribe (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:27052:52)
    at file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:34260:10
    at file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:34274:4
    at e2.withAsyncContext (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:7332:14)
    at setup (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:34251:64)
    at px.setup (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:34283:96)
    at callWithErrorHandling (file:///my-dir/.wrangler/tmp/dev-P05VER/m10vftjxpip.js:5254:17)
    ```
