### ISSUE TITLE
NextJS Not Subscribing to RealTime (subscription state is "closed")

### ISSUE THREAD

**Issue by kmallari** [supabase/realtime-js#168]
# Bug report

## Describe the bug

I'm trying to subscribe to a realtime table in Supabase. For some reason, the subscription is not working so database changes aren't being reflected to my NextJS app. I've tried logging the listener, and the state of the listener is "closed."

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I have a useEffect hook in my Next page:

```javascript
useEffect(() => {
    let gameListener = supabase
      .from("games")
      .on("*", (payload) => {
        console.log("PAYLOAD", payload.new);
      })
      .subscribe();

    const subscriptions = supabase.getSubscriptions();
    console.log("SUBS", subscriptions);

    return () => {
      supabase.removeSubscription(gameListener);
    };
  }, []);
```

## Expected behavior

I expect to subscribe to the changes and expect the state of the subscription to be "joined" instead of "closed."

## Screenshots

Output of subscription
![](https://i.imgur.com/yRRBkmQ.png)

Screenshot of my db
![](https://i.imgur.com/qTVPvAd.png)

## System information

- OS: Windows 10 Pro
- Browser: Brave
- Version of supabase-js: 1.35.4
- Version of Node.js: 18.0.3

**Comment by kmallari** [comment]
I was able to solve the issue by changing strict mode in my `next.config.js` to false.
```javascript
const nextConfig = {
  reactStrictMode: false,
  swcMinify: true,
};
```
I found the solution [here](https://stackoverflow.com/questions/60618844/react-hooks-useeffect-is-called-twice-even-if-an-empty-array-is-used-as-an-ar), where it says that 

> StrictMode renders components twice (on dev but not production) in order to detect any problems with your code and warn you about them (which can be quite useful).

Because strict mode was true, it was making my component render twice, which messes up the real-time subscription to my database.

**Comment by jordanful** [comment]
I am experiencing this issue, and changing `reactStrictMode` to `false` does not resolve it.

**Comment by w3b6x9** [comment]
@jordanful take a look at https://github.com/supabase/realtime-js/issues/169 and if that doesn't resolve your issue then please create another issue. thanks!

**Comment by w3b6x9** [comment]
Hey everyone, I have addressed the issue. Please see https://github.com/supabase/realtime-js/issues/169#issuecomment-1223026406 for context.
