### ISSUE TITLE
realtime-js allows only one subscription at a time

### ISSUE THREAD

**Issue by pixtron** [supabase/realtime-js#180]
# Bug report

## Describe the bug

Currently it is not possible to have more then one subscription on `postgres_changes` 

### two subscriptions on all postgres-changes.

Only `channel2` will log changes. `channel1` never receives changes.

```ts
const channel1 = supabase
  .channel("db-changes")
  .on("postgres_changes", { event: "*", schema: "*" }, (payload: any) =>
    console.log("Postgres change channel 1", payload)
  );

channel1.subscribe();

const channel2 = supabase
  .channel("db-changes")
  .on("postgres_changes", { event: "*", schema: "*" }, (payload: any) =>
    console.log("Postgres change channel 2", payload)
  );

channel2.subscribe();
```

### two subscriptions on selected postgres-changes.

Only `channel2` will log changes. `channel1` never receives changes.

```ts
const channel1 = supabase
  .channel("db-changes")
  .on("postgres_changes", { event: "UPDATE", schema: "public", table: "cities" }, (payload: any) =>
    console.log("City updated", payload)
  );

channel1.subscribe();

const channel2 = supabase
  .channel("db-changes")
  .on("postgres_changes", { event: "UPDATE", schema: "public", table: "countries" }, (payload: any) =>
    console.log("Country updated", payload)
  );

channel2.subscribe();
```

## Expected behavior

All channels should get notifications, until they have been unsubscribed (eg `supabase.removeChannel(channel1)`)

## System information

- Version of supabase-js: 2.0.0-rc.5

**Comment by w3b6x9** [comment]
@pixtron Realtime does not allow duplicate channel names per connected client so this is the intended effect. You can, however, name your channels whatever you like so the skies the limit.

**Comment by w3b6x9** [comment]
> A warning to the console channel with ${channelName} already exists. Overriding existing channel would be a nice hint tho.

@pixtron good feedback! will find the best way to surface this so devs are aware. thanks!
