### ISSUE TITLE
`presence` not working on the docker image

### ISSUE THREAD

**Issue by bhvngt** [supabase/realtime-js#183]
# Bug report

## Describe the bug

Are new [broadcast](https://supabase.com/docs/guides/realtime/broadcast) and [presence](https://supabase.com/docs/guides/realtime/presence) behaviours been rolled out on the docker image? 

When I use the code snippet from the official documentation, I get status as `ok`. But no logs of online users or broadcast message is seen on the browser console. 

In case of a `broadcast`, I get `ok` message in a `loop` even if I remove the `setInterval` based timer. No `payload` is logged.

## To Reproduce

Running  code snippets from official documentation - [broadcast](https://supabase.com/docs/guides/realtime/broadcast) and [presence](https://supabase.com/docs/guides/realtime/presence) does not work on the docker image. 

However, the same works when key from supabase.com project site is provided.

## Expected behaviour

Expecting docker image to work for `presence` and `broadcast` functionality for local development.

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: v2.0.0-rc.6
- Version of Node.js: v18.7.0

**Comment by w3b6x9** [comment]
@bhvngt Broadcast and Presence are not yet available on the docker image. See https://github.com/supabase/realtime/issues/284#issuecomment-1224908325.

**Comment by bhvngt** [comment]
@w3b6x9 Would you have any rough ETA on the availability on the docker image?

**Comment by w3b6x9** [comment]
@bhvngt I don't have a good estimate. Right now, we're transitioning all Supabase projects over to a new Realtime cluster. We're planning to complete this by end of week. Perhaps we'll get started on moving the codebase over to [Realtime](https://github.com/supabase/realtime). I wanna say another 3-5 weeks minimum.
