### ISSUE TITLE
Duplicate and unknown users while trying out presence on supabase project

### ISSUE THREAD

**Issue by bhvngt** [supabase/realtime-js#184]
# Bug report

## Describe the bug

While trying out `presence` code snippet from the official [documentation](https://supabase.com/docs/guides/realtime/presence), I get duplicate and unknown users as online users even though I am loading only a single page.

## To Reproduce

I ran following code snipeet

```javascript
        const supabase = createClient(supabaseUrl, anonKey);
        const channel = supabase.channel('online-users')
        channel
          .on('presence', {event: 'sync'}, () => {
              console.log('currently online users', channel.presenceState())
          })
          .on('presence', {event: 'join'}, ({newUser}) => {
              console.log('a new user has joined', newUser)
          })
          .on('presence', {event: 'leave'}, ({leftUser}) =>
            console.log('a user has left', leftUser)
          )
          .subscribe(async (status) => {
              if (status === 'SUBSCRIBED') {
                  const user_name = getRandomUser();
                  console.log(`user_name`, user_name);
                  const status = await channel.track({user_name})
                  console.log(status)
              }
          })
```

## Expected behavior

I was expecting a single user `Bob` as an online user

## Screenshots

![image](https://user-images.githubusercontent.com/79074469/187591605-a33d16cc-8b17-40e4-8579-0c2a8a47f022.png)

## System information

- OS: MacOs
- Browser (if applies): chrome
- Version of supabase-js: 2.0.0-rc.6
- Version of Node.js: v18.7

## Additional Context

The number of users keep changing. Not sure if this is to do with some lingering connections. I tried to reload the page after few min. Still get the same result.

**Comment by w3b6x9** [comment]
@bhvngt Can you please share how you're cleaning up the channel? I'm assuming you're using React.

**Comment by bhvngt** [comment]
@w3b6x9 I am just reloading the page without using any explicit code to cleanup channel. I am using svelte. Code snippet given is the only code running on the page.

**Comment by w3b6x9** [comment]
@bhvngt I want to preface this by writing that I haven't used Svelte at all. I think you should clean up the channel in `onDestroy` by calling `supabase.removeChannel(channel)`.

**Comment by bhvngt** [comment]
Thanks @w3b6x9. I tried with `supabase.removeChannel(channel)` inside `onDestroy` and now it is working as expected.
