### ISSUE TITLE
reconnection possible bug ?

### ISSUE THREAD

**Issue by smarcet** [supabase/realtime-js#187]
hello guys
i was looking at https://github.com/supabase/realtime-js/blob/master/src/RealtimeSubscription.ts source code and i have this doubt.
here
https://github.com/supabase/realtime-js/blob/10228a3d7cb87897751952dfd2f39d0a09f4cdac/src/RealtimeSubscription.ts#L49
when the realtime subscription got an error its trigger the reconnection timer, but timer callback is asking here
https://github.com/supabase/realtime-js/blob/10228a3d7cb87897751952dfd2f39d0a09f4cdac/src/RealtimeSubscription.ts#L64
for this.socket.isConnected(), what if the socket is not connected ? then the realtime subscription it's left on a broken state ? ( like not receiving any more updates from server till subscription is restarted by client code ?)
much thanks in advance

**Comment by w3b6x9** [comment]
> what if the socket is not connected ?

@smarcet when the socket is not properly disconnected then it'll continuously try to reconnect, and once this is successful, then each subscription will then be able to rejoin. You can take a look at https://github.com/supabase/realtime-js/blob/702594effeeb94e106c7f9518b1366ff6b89a12a/src/RealtimeClient.ts#L388.
