### ISSUE TITLE
Realtime is not working on React Project

### ISSUE THREAD

**Issue by yokowasis** [supabase/realtime-js#188]
# Bug report

## Describe the bug

The realtime listener doesn't get fired when using it on react project. Works fine on normal nodejs project.

## To Reproduce

[SandBox](https://codesandbox.io/s/supabase-subscribe-36hbk5?file=/src/index.js)

## Expected behavior

The script is fired, and the react component state is changed.

**Comment by w3b6x9** [comment]
@yokowasis doesn't look like you're running into [this issue](https://github.com/supabase/realtime-js/issues/169) judging from the react version you're using in that codesandbox.

can you please submit a support ticket and include your supabase project ref? https://app.supabase.com/support/new

**Comment by yokowasis** [comment]
> @yokowasis doesn't look like you're running into [this issue](https://github.com/supabase/realtime-js/issues/169) judging from the react version you're using in that codesandbox.
> 
> can you please submit a support ticket and include your supabase project ref? https://app.supabase.com/support/new

Looks like I did. I modify my code to something like this, and it works, at least on localhost. Haven't tested it on production. 

```
  const first = useRef(true);

  useEffect(() => {
    if (first.current) {
      first.current = false;
    } else {
      supabase
        .from("datatest")
        .on("*", (payload) => {
          console.log(payload);
        })
        .subscribe();
    }
    })();

    return () => {
      console.log("DISMISS");
    };
  }, []);

```
