### ISSUE TITLE
type information is wrong for RealtimePostgresChangesPayload 

### ISSUE THREAD

**Issue by samuba** [supabase/realtime-js#201]
# Bug report

Not sure if this belongs here or in supabase/supabase-js.

## Describe the bug

When using realtime subscriptions with v2.0.0 of supabase-js the payload type (`RealtimePostgresChangesPayload`) does not match how the payload actually looks like.

When inspecting the payload in the browser it looks like this:
![image](https://user-images.githubusercontent.com/1148424/196139030-976225a5-caf7-4e9d-b1a4-d60f69173389.png)

But `RealtimePostgresChangesPayload` looks like this and does not contain e.g. `record`, `old_record`, `columns` etc from the actual payload. 

```ts
export type RealtimePostgresChangesPayload<T extends { [key: string]: any }> = {
  schema: string
  table: string
  commit_timestamp: string
  eventType:
    | `${REALTIME_POSTGRES_CHANGES_LISTEN_EVENT.INSERT}`
    | `${REALTIME_POSTGRES_CHANGES_LISTEN_EVENT.UPDATE}`
    | `${REALTIME_POSTGRES_CHANGES_LISTEN_EVENT.DELETE}`
  new: T | {}
  old: Partial<T> | {}
  errors: string[]
}
```

Even worse: `old` and `new` are present but always `undefined`. So with the current state of the type I do not even get the data I need.

## Expected behavior

`RealtimePostgresChangesPayload` should reflect the actual payload type.

## System information

- Version of supabase-js: 2.0.0
- Version of Node.js: 16.14.2

**Comment by w3b6x9** [comment]
@samuba thanks for reporting this! We have a PR open that addresses this: https://github.com/supabase/realtime-js/pull/199. Will get this released shortly after approval.

**Comment by w3b6x9** [comment]
> Even worse: old and new are present but always undefined

@samuba hmm that is super weird b/c that should never be the case. are you self-hosting or have a project at supabase.com?

**Comment by samuel-bach** [comment]
Nice that it is already addressed. 👍 

>@samuba hmm that is super weird b/c that should never be the case. are you self-hosting or have a project at supabase.com?
I encountered this locally using the CLI have not tested on supabase.com yet.

**Comment by samuba** [comment]
Nice that this is already addressed. 👍

>@samuba hmm that is super weird b/c that should never be the case. are you self-hosting or have a project at supabase.com?

I encountered this locally using the CLI have not tested on supabase.com yet.

**Comment by samuel-bach** [comment]
By the way: The docs are currently not documenting the payload type at all. Only the parameters. https://supabase.com/docs/reference/javascript/subscribe

**Comment by samuba** [comment]
By the way: The docs are currently not documenting the payload type at all. Only the parameters. https://supabase.com/docs/reference/javascript/subscribe

**Comment by w3b6x9** [comment]
> I encountered this locally using the CLI v1.6.0.

@samuba existing CLI's Realtime is not yet compatible with supabase-js v2. Try it with the hosted Supabase when ready.

> The docs are currently not documenting the payload type at all. Only the parameters.

Thanks, will take a look.

**Comment by corasan** [comment]
@w3b6x9  not sure if this is related but I get `Type '"UPDATE"' is not assignable to type '"DELETE"'`

Code:

```javascript
supabase
      .channel('public:profiles')
      .on(
        'postgres_changes',
        {
          event: 'UPDATE', // Type '"UPDATE"' is not assignable to type '"DELETE"'
          scheme: 'public',
          table: 'profiles'
        },
        payload => {
          ....
        },
      )
      .subscribe()
```

**Comment by w3b6x9** [comment]
@corasan which version of `realtime-js` are you on? Are you on [v2.1.0](https://github.com/supabase/realtime-js/releases/tag/v2.1.0)?

**Comment by jsbrain** [comment]
I'm facing the same issue as described in https://github.com/supabase/supabase-js/issues/640.

Continuing the discussion here I'm using self-hosted, my deployment is up-to-date with [docker/docker-compose.yml](https://github.com/supabase/supabase/blob/0b6f6c1ed4f9e646d6b6b341354b013ceea763fa/docker/docker-compose.yml).

**Comment by jsbrain** [comment]
Temporary workaround for anyone stumbling over this:

```ts
import { REALTIME_POSTGRES_CHANGES_LISTEN_EVENT } from '@supabase/supabase-js';

export enum PostgresColumnTypes {
  abstime = 'abstime',
  bool = 'bool',
  date = 'date',
  daterange = 'daterange',
  float4 = 'float4',
  float8 = 'float8',
  int2 = 'int2',
  int4 = 'int4',
  int4range = 'int4range',
  int8 = 'int8',
  int8range = 'int8range',
  json = 'json',
  jsonb = 'jsonb',
  money = 'money',
  numeric = 'numeric',
  oid = 'oid',
  reltime = 'reltime',
  text = 'text',
  time = 'time',
  timestamp = 'timestamp',
  timestamptz = 'timestamptz',
  timetz = 'timetz',
  tsrange = 'tsrange',
  tstzrange = 'tstzrange',
}

export interface PostgresColumn {
  name: string;
  type: `${PostgresColumnTypes}`;
}

export interface RealtimeEventPayloadTMP<
  TRecord extends { [key: string]: any },
> {
  columns: PostgresColumn[];
  commit_timestamp: string;
  errors: string[];
  old_record: TRecord;
  record: TRecord;
  schema: string;
  table: string;
  type: `${REALTIME_POSTGRES_CHANGES_LISTEN_EVENT}`;
}

const channelId = `public:app_users`;
const channel = supabaseClient
  .channel(channelId)
  .on<app_users_entity>(
    'postgres_changes',
    {
      schema: 'public',
      event: REALTIME_POSTGRES_CHANGES_LISTEN_EVENT.UPDATE,
    },
    (payload) => receivedDatabaseEvent(payload as any),
  )
  .subscribe();

const receivedDatabaseEvent = (
  payload: RealtimeEventPayloadTMP<app_users_entity>,
) => {
  payload.record // type is app_users_entity
};
```

**Comment by guillaume86** [comment]
Same issue here with the self hosted docker images and realtime-js@2.1.0. Any news for a update?

**Comment by jsbrain** [comment]
> Both CLI + self-host Realtime images are up to date so this shouldn't be an issue anymore.

Cannot verify because realtime deployment for self-hosted does not work currently, due to https://github.com/supabase/realtime/issues/415

**Comment by meenie** [comment]
@w3b6x9, I'm running `supabase` cli at 1.75.3 and `@supabase/supabase-js` at `2.26.0` and the types are using the older `payload.new` and `payload.old` locally. You can see here the types are still incorrect: https://github.com/supabase/realtime-js/blob/c9dc9c953cb6bb3e9440749d393e944b63a0a0f9/src/RealtimeChannel.ts#L43-L48 So I don't think this is fixed.
