### ISSUE TITLE
Broadcast .send() calls get ignored if not awaited

### ISSUE THREAD

**Issue by enyo** [supabase/realtime-js#205]
# Bug report

## Describe the bug

When you call `supabaseChannel.send({...})` multiple times without awaiting it, subsequent calls are simply ignored.

## To Reproduce

Create a supabase realtime channel, invoke `.send()` multiple times (without `await`) and inspect the websocket connection. Only the first one goes through.

## Expected behavior

I would expect the calls to be batched and either sent together, or the channel to loop over them for me.

**Comment by enyo** [comment]
I realised that I could reduce the rate limit like this:

```js
createClient(url, anonKey, { realtime: { params: { eventsPerSecond: 200 } } })
```

This works for now, and I have implemented my own wrapper that makes sure events are throttled to not exceed this rate limit.

I would be grateful to get a confirmation that is the best way to solve this. Other than that this issue can be closed.

**Comment by w3b6x9** [comment]
> I realised that I could reduce the rate limit like this:
> 
> ```js
> createClient(url, anonKey, { realtime: { params: { eventsPerSecond: 200 } } })
> ```
> 
> This works for now, and I have implemented my own wrapper that makes sure events are throttled to not exceed this rate limit.
> 
> I would be grateful to get a confirmation that is the best way to solve this.

@enyo that's correct, you can tweak the `eventsPerSecond` depending on your use case. This was just a basic rate limiter we put in place client-side but there are more sophisticated rate limits on the server. You can check out [Realtime Rate Limits](https://supabase.com/docs/guides/realtime/rate-limits) for additional information.

I'm going to close this issue but feel free to reopen if needed.
