### ISSUE TITLE
Multiple CORS errors on Codesandbox

### ISSUE THREAD

**Issue by netgfx** [supabase/realtime-js#219]
# Bug report

## Describe the bug

There are multiple CORS errors thrown when trying to listen to DB changes in a Codesandbox environment

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Reproducible here: https://codesandbox.io/s/lucid-lamport-zb3yqn?file=/src/API.js

## Expected behavior

There are no errors and changes are logged normally.

## Screenshots

![image](https://user-images.githubusercontent.com/864248/212746302-30f68e7f-6f27-4b19-a7fc-617093089c36.png)

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js: 2.4.0
- Version of Node.js: Unknown, whatever is Codesandbox using

## Additional context

Locally the same exact project works fine.

**Comment by netgfx** [comment]
Heard back from the codesandbox team

```
I've had a look at the sandbox and discovered that our browser runtime incorrectly resolves a dependency of `supabase/realtime-js` to use the node.js version of websocket instead of the browser version.

To workaround this for now you can pass the following settings to the supabaseClient:

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  realtime: {
    transport: window.WebSocket
  }
});

A working sandbox example: https://codesandbox.io/s/websocket-browser-node-failure-8ms06m

I've also logged this issue in our internal backlog and will try to get this fixed as soon as possible.
```

Posting it here in case anyone else comes asking.

**Comment by hash-bang** [comment]
I can confirm that this bug still exists as of the upstream `@supabase/supabase-js@2.37.0` NPM. I'm not sure if that NPM just needs this modules version bumping?

The fix posted by @netgfx seems to resolve this problem though.

**Comment by hash-bang** [comment]
As of `@supabase/supabase-js@2.43.2` the above workaround is no longer needed.
