### ISSUE TITLE
_throttle in realtimeclient.js doesn't work as expected in microsoft edge

### ISSUE THREAD

**Issue by vqt123** [supabase/realtime-js#220]
# Bug report
There's something about throttling that doesn't work in microsft edge in the realtimeclient->_throttle method

## Describe the bug

On edge, if i send a lot of events, this method gets trapped with inThrottle being set to true, and the timeout which is suppose to reset the flag doesn't happen, and only is reset once the timeout is reached.

rate limiting seems to work just fine on chrome and brave

## To Reproduce

connect to a channel
broadcast a message on mouse move
set the limit to 30 events per second 
notice that rate limit is hit after a few seconds on edge (oddly enough, clicking the mouse button fixes the issue for a fewseconds)

works as expeted on chrome and brave.

narrowed down some weird edge behavior with setTimeout ?

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

events  per second limit should be kept, but rate limiting takes over on edge

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

 [New Recording - 1/19/2023, 11:33:13 PM](https://vimeo.com/791040527/91f2213b9f)

**Comment by w3b6x9** [comment]
@vqt123 I'm having a hard time grasping what your issue is. So you're using Edge but you're unable to send 30 messages per second? However, Chrome and Brave are both able to send 30 messages per second? You suspect that `setTimeout` is not functioning properly to reset inThrottle to `false`?

**Comment by w3b6x9** [comment]
@vqt123 does this sound like what you're experiencing? https://github.com/MicrosoftEdge/WebView2Feedback/issues/3024#issue-1478426662

**Comment by vqt123** [comment]
yes this is the issue. 

edge is
Microsoft Edge
Version 109.0.1518.55 (Official build) (64-bit)

**Comment by vqt123** [comment]
@w3b6x9 in my recording i tried to show how broadcast messages sent from edge are much more rate limited vs messages sent from the brave browser. Both are using the same code and connected to the same channel

**Comment by vqt123** [comment]
for better edge support, the realtimeclient throttle function should probably be updated to not be reliant on set timeout, atleast until edge identifies and fixes the issue.

**Comment by w3b6x9** [comment]
@vqt123 what I can do is provide the option to disable the built-in limiter completely and enable devs to do it themselves so they don't unintentionally send more messages than desired. I'll get that out next week.

**Comment by w3b6x9** [comment]
@vqt123 you can now pass in a negative number (e.g. -1) for `eventsPerSecond` and that should circumvent `setTimeout`.
