### ISSUE TITLE
Docs for RealtimeChannelOptions inconsistent with implementation

### ISSUE THREAD

**Issue by mkcode** [supabase/realtime-js#227]
# Bug report

The documentation on this repo is inconsistent the Types and implementation for RealtimeChannelOptions.

### The docs indicate that no `config` keyword is needed for the `channel` method:
https://github.com/supabase/realtime-js/blob/63242ff54958ecedb924345d3c07ffbff69cf830/README.md?plain=1#L117

### The type defs and implementation disagree:
https://github.com/supabase/realtime-js/blob/63242ff54958ecedb924345d3c07ffbff69cf830/src/RealtimeChannel.ts#L13-L14

and

https://github.com/supabase/realtime-js/blob/63242ff54958ecedb924345d3c07ffbff69cf830/src/RealtimeChannel.ts#L132-L138

Not sure if the docs should be updated or the code. Let me know and I can submit a PR!

**Comment by w3b6x9** [comment]
@mkcode thanks for pointing this out! it was indeed an issue with the readme so i updated it.
