### ISSUE TITLE
BUG: Fatal error listening on DB Changes, DELETE

### ISSUE THREAD

**Issue by nkreiger** [supabase/realtime-js#238]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [  ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

/app/node_modules/@supabase/realtime-js/dist/main/lib/transformers.js:51
    return Object.keys(record).reduce((acc, rec_key) => {
                  ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.convertChangeData (/app/node_modules/@supabase/realtime-js/dist/main/lib/transformers.js:51:19)
    at RealtimeChannel._getPayloadRecords (/app/node_modules/@supabase/realtime-js/dist/main/RealtimeChannel.js:475:40)
    at /app/node_modules/@supabase/realtime-js/dist/main/RealtimeChannel.js:361:93
    at Array.map (<anonymous>)
    at RealtimeChannel._trigger (/app/node_modules/@supabase/realtime-js/dist/main/RealtimeChannel.js:348:16)
    at /app/node_modules/@supabase/realtime-js/dist/main/RealtimeClient.js:295:47
    at Array.forEach (<anonymous>)
    at /app/node_modules/@supabase/realtime-js/dist/main/RealtimeClient.js:295:18
    at Serializer.decode (/app/node_modules/@supabase/realtime-js/dist/main/lib/serializer.js:14:20)

## To Reproduce

// setup channel handler
    targets.forEach((tgt) => {
        // channel.on('postgres_changes', { event: '*', schema: 'system', table: 'test' }, DefaultHandler);
        channel.on('postgres_changes', { event: tgt.event, schema: tgt.schema, table: tgt.table }, handle);
    })
    
    Delete something from the table test DB

## Expected behavior

I receive the removed record, not an error.

## System information

- Version of supabase-js: 2.7.2

**Comment by nkreiger** [comment]
This happens if you have an authentication issue, the record comes back as null...maybe this could be handled better?

closing.

**Comment by evhan** [comment]
For anyone who finds this issue (which was still an issue, regardless of whether there was an authentication problem, the procedure was still receiving values that it did not account for correctly), it looks like this has been fixed in #539.
