### ISSUE TITLE
Calling channel.track with new data on existing presence triggers leave+join 

### ISSUE THREAD

**Issue by wyozi** [supabase/realtime-js#244]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Calling `RealtimeChannel#track` multiple times with differing values triggers leave/join events each time.

## To Reproduce

```
channel.track({foo: "bar"})
await sleep(100);
channel.track({foo: "baz"})
```

causes a WS message something like 

```
{"event":"presence_diff","payload":{"joins":{"u/058c52":{"metas":[{"phx_ref":"F3g3A5Sb9ynNKjbE","phx_ref_prev":"F3g3At6RfjDNKo5n","foo":"baz"}]}},"leaves":{"u/058c52":{"metas":[{"phx_ref":"F3g3At6RfjDNKo5n","foo":"bar"}]}}},"ref":null,"topic":"realtime:room_1"}
```

and thus triggers leave and join messages in quick succession with the same user id.

## Expected behavior

A simple `track` call should not trigger leave and joins, but just sync.

## System information

- Version of supabase-js: "@supabase/supabase-js": "^2.31.0",
- Using supabase cloud

**Comment by w3b6x9** [comment]
@wyozi this is how Realtime Presence works. When you call `.track` again Presence treats it like an update but will report it to clients as leave and join. That's why you see both a `phx_ref` and `phx_ref_prev` to signal that there was an update operation.
