### ISSUE TITLE
Allow export of types used in realtime package

### ISSUE THREAD

**Issue by kyeshmz** [supabase/realtime-js#258]
# Chore

## Describe the chore
I need to take care the lifetime cycle of a realtime channel and make the player wait if it is not connected yet.

```
export enum CHANNEL_STATES {
  closed = 'closed',
  errored = 'errored',
  joined = 'joined',
  joining = 'joining',
  leaving = 'leaving',
}
``` 
inside of constants.

**Comment by filipecabaco** [comment]
Thank you for reporting. Released today

https://github.com/supabase/supabase-js/pull/893
