### ISSUE TITLE
Allow .on broadcast listen to be able to cast type T

### ISSUE THREAD

**Issue by kyeshmz** [supabase/realtime-js#259]
# Chore

## Describe the chore

Currently, if you want to cast what the payload would be for a .on broadcast with a T type, it automatically becomes a postgres_changes for the type. I would like to type what kind of type a payload is broadcasted with to a certain event name.

I want to do something like
```
export interface RealtimeType {
  type: REALTIME_LISTEN_TYPES
  event: string
  payload?: any
  [key: string]: any
}

export interface GameStateRealtime extends RealtimeType {
  payload: {
    gameState: GameState
  }
}
```

## Additional Info
<img width="875" alt="Screenshot 2023-10-19 at 8 02 35 PM" src="https://github.com/supabase/realtime/assets/12763472/9a08b1cf-477e-4b7f-bdbb-4ff61862d79a">

**Comment by filipecabaco** [comment]
Thank you for reporting. Released today

https://github.com/supabase/supabase-js/pull/893
