### ISSUE TITLE
Supabase RealtimeJS closing channel because of mismatch between server and client bindings for postgres changes

### ISSUE THREAD

**Issue by tayfunyil** [supabase/realtime-js#264]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using realtime-js in my Ionic Vue project. I am instantiating the client as follow:

```
import { RealtimeClient } from '@supabase/realtime-js'`

const client = new RealtimeClient("ws://{...}.supabase.co/realtime/v1", {
  params: {
    apikey: ""
  },
})
```

In my onMounted hook I try to subscribe as follows:

```
onMounted(() => {
  const channel = client.channel('test-channel', {})

  channel.subscribe((status, err) => {
    if (status === 'SUBSCRIBED') {
      console.log('Connected!')
    }

    if (status === 'CHANNEL_ERROR') {
      console.log(`There was an error subscribing to channel: ${err.message}`)
    }

    if (status === 'TIMED_OUT') {
      console.log('Realtime server did not respond in time.')
    }

    if (status === 'CLOSED') {
      console.log('Realtime channel was unexpectedly closed.')
    }
  })

  channel.on('postgres_changes', { event: '*', schema: 'public' }, (payload) => {
    console.log('All changes in public schema: ', payload)
  })
}) 
```

The result in my browser is then:

> Realtime channel was unexpectedly closed. There was an error subscribing to channel: mismatch between server and client bindings for postgres changes

## Expected behavior

I was expecting to receive events

## System information

- OS: Mac
- Browser: Chrome
- Version of supabase-js: 2.38.0
- Version of realtime-js: 2.8.4
- Version of Node.js: 20.7.0

## Additional context

I am developing a Ionic app using Vue3. I switched to other Supabase instances, turned off RLS completely but nothing changed.

**Comment by filipecabaco** [comment]
@tayfunyil that error seems to be related with your database 🤔 could you please open a ticket via Support so we can check your supabase project?
