### ISSUE TITLE
[2.9.0] Module breaks in server context (SSR)

### ISSUE THREAD

**Issue by r0skar** [supabase/realtime-js#266]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using the latest package `@supabase/supbabase-js` with [solid-start](https://start.solidjs.com), following error is thrown when running the application:

```
file:///vault/dev/work/xxxxx/dist/server.js:124124
? WebSocket
^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/vault/dev/work/xxxxxx/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

The code at line `124124` in the dist file:

```
const WebSocketVariant = NATIVE_WEBSOCKET_AVAILABLE
    ? WebSocket
    : require('ws');
```

This seems to be related to [this commit](https://github.com/supabase/realtime-js/commit/57d9b65b7107e7f6f301703430968545c4a82141). Downgrading the `realtime-js` package to `2.8.4` fixes the issue.

## Expected behavior

The package should work in server context.

## System information

- OS: Linux
- Browser (if applies) N/A
- Version of supabase-js: 2.39.0
  - Version of realtime-js: 2.9.0
- Version of Node.js: 20.9.0

## Additional context

My package.json type is set to `module`.

**Comment by mhevery** [comment]
The offending line is here: https://github.com/supabase/realtime-js/commit/57d9b65b7107e7f6f301703430968545c4a82141#diff-f5a6b192eb9d6c05f61c33d8629b814ad893fbfb729bfa7af9b226e5c87d2e85R66

It contains `require` which ends up as ESM module https://www.unpkg.com/browse/@supabase/realtime-js@2.9.0/dist/module/RealtimeClient.js

This causes an issue because if the node loads ESM and then sees `require` it falls with the above error.

The correct fix is to use dynamic `import('ws')` in that location and let the bundler downlevel it to `require` for CJS.

**Comment by w3b6x9** [comment]
> The correct fix is to use dynamic `import('ws')` in that location and let the bundler downlevel it to `require` for CJS.

@mhevery can you look at this PR and give me your thoughts? we were discussing this internally and was worried about `import`ing there, waiting for promise to resolve, while the imported `ws` module default is set when instantiating the class.

PR: https://github.com/supabase/realtime-js/pull/267

**Comment by ksjogo** [comment]
We were also running into this when deploying to cloudflare and had to fix to the older version.

The PR above indeed seems to potentially introduce async issues.
Couldn't you use isomorphic-ws to differentiate the import at bundling time?

**Comment by mhevery** [comment]
https://github.com/supabase/realtime-js/pull/267#pullrequestreview-1774095369

**Comment by w3b6x9** [comment]
@r0skar @ksjogo give this fix a try and see if it fixes your issue: https://github.com/supabase/realtime-js/releases/tag/v2.9.1.
