### ISSUE TITLE
[2.9.0] Breaking Vercel Edge Routes building

### ISSUE THREAD

**Issue by robipop22** [supabase/realtime-js#268]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using the latest version of supabase-js that is updating the realtime-js to 2.9.0 breaks the builds on Vercel specifically on the "Edge" routes in a Remix App.
It's not a Remix or Vercel bug, is about the unsupported module ws added by this [PR](https://github.com/supabase/realtime-js/pull/263/files)

## To Reproduce

Initialize a new Project with any framewokr, Remix, Next. 
Add supabase-js latest version
Convert 1 route to an "edge" route and try to use supabase-js. The build will break with the following:

Error: The Edge Function "api/route" is referencing unsupported modules:
--
12:48:23.508 | - @supabase: ws

## Expected behavior

Updating to the latest version should not break the current builds and the app should work with latest version without switching the Edge routes to Serverless

## System information

Vercel deployment using nodejs v18.

## Additional context

For now 1 workaround we applied is to override the version for realtime-js to "2.7.4".

```"pnpm": {
		"overrides": {
			"@supabase/realtime-js": "2.7.4"
		}
	},
```

**Comment by w3b6x9** [comment]
@robipop22 give this fix a try and see if it fixes your issue: https://github.com/supabase/realtime-js/releases/tag/v2.9.1.
