### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by aimagination-dev** [supabase/realtime-js#270]
# Getting below error after creating app with next js and supabase

 ⚠ ../node_modules/node-gyp-build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
../node_modules/node-gyp-build/index.js
../node_modules/bufferutil/index.js
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/wrapper.mjs
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/ssr/dist/index.mjs
./utils/supabase/server.ts
./app/login/page.tsx

**Comment by w3b6x9** [comment]
@aimagination-dev which version of `realtime-js` are you on? this should be fixed with v2.9.1.

**Comment by aimagination-dev** [comment]
I have latest version of realtime-js but still hitting the issue

  "dependencies": {
    "@supabase/auth-helpers-nextjs": "^0.8.7",
    "@supabase/auth-ui-react": "^0.4.6",
    "@supabase/auth-ui-shared": "^0.1.8",
    "@supabase/realtime-js": "^2.9.1",
    "@supabase/supabase-js": "^2.39.2",
