### ISSUE TITLE
Invalid API key Double check your Supabase `anon` or `service_role` API key

### ISSUE THREAD

**Issue by thecode-master-sy** [supabase/realtime-js#271]
# Bug report
I get this error when i am trying to use the supabase broadcast to send messages to a channel, at first it was working but as of recently i start seeing this error, how do i resolve this please.

my supabase anon key and url are loaded properly, its working for auth but for realtime it fails

how to repelicate:

` const supabase = createClientComponentClient();`
`  channel.send({
                type: 'broadcast',
                event: 'message',
                payload: newMessage,
            })`

error i am getting
`{
    "message": "Invalid API key",
    "hint": "Double check your Supabase `anon` or `service_role` API key."
}`

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by w3b6x9** [comment]
@thecode-master-sy can you share what's going on inside `createClientComponentClient()`? also, can you submit a support ticket and share your project ref so we can take a look at your project's specifics?

**Comment by thecode-master-sy** [comment]
createClientComponentClient() is coming from supabase-nextjs/authhelpers package

**Comment by w3b6x9** [comment]
> @Mukhammadali For now, you can force the anon_key: `supabase.realtime.accessToken = env.SUPABASE_ANON_KEY!; const channel = supabase.channel('channel') channel.send({ type: 'broadcast', event: 'example', payload: { }, })`

be careful with this move as it can break Realtime Postgres Changes listening when tables have RLS enabled and policies set.

`realtime-js` will send to Realtime server the new token set, in this case `anon` token, during the next heartbeat which could prevent new database changes from reaching the client depending on your rls policies.

**Comment by w3b6x9** [comment]
we're also aware of this issue. the problem here is that the `accessToken` gets updated to user's `authenticated` token and our API gateway won't allow it as we're hard checking against your project's `anon` and `service_role` tokens when hitting the broadcast endpoint.

**Comment by Mukhammadali** [comment]
I am using local patch via patch-package. @w3b6x9  with rls on or off, with my fix it is working as expected. What do you think about the fix I raised in the PR?
https://github.com/supabase/realtime-js/pull/273

**Comment by w3b6x9** [comment]
@Mukhammadali thanks, it's a good stopgap until we decide on how we wanna do it in our API Gateway.

**Comment by w3b6x9** [comment]
this should be addressed in [realtime-js v2.9.2](https://github.com/supabase/realtime-js/releases/tag/v2.9.2). thanks for all your feedback!
