### ISSUE TITLE
Expose "system" as a type.

### ISSUE THREAD

**Issue by kyeshmz** [supabase/realtime-js#291]
# Chore

## Describe the chore
Currently there is no type for "system", only the 3 main available ones that are here.
https://supabase.com/docs/guides/realtime

But for users using postgres changes, it is essential to be able to restart the connection.
This is also something discussed in #234 and #5641, but as the solution is heavy, this might be something to ease the pain for now.
https://github.com/GaryAustin1/Realtime2/blob/main/src/app.js#L57

https://github.com/orgs/supabase/discussions/5641

This chore might also extend to creating documentation for what "system" is. 

## Additional context

Add any other context or screenshots that help clarify the task.

**Comment by geoguide** [comment]
Oh is this my problem also?! https://github.com/supabase/realtime-js/issues/416

**Comment by kyeshmz** [comment]
Seems like the exact same.

**Comment by filipecabaco** [comment]
great call, I'm finishing the work to test out https://github.com/supabase/realtime-js/issues/121 and I will pick this one up

**Comment by filipecabaco** [comment]
FYI PR merged and available in version 2.10.5
