### ISSUE TITLE
Issues with types and ESM/CJS module resolution in Node.js

### ISSUE THREAD

**Issue by ericallam** [supabase/realtime-js#424]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

There are a number of different issues around type resolution & module resolution with this library in Node.js. As this package is a dependency of `@supabase/supabase-js`, and is imported in the main `@supabase/supabase-js` barrel file, then anyone trying to use `@supabase/supabase-js` in Node.js will face these issues unless they use a bundler that papers over these issues (I'm not sure how?).

## To Reproduce

I've created a repo that reproduces the different issues that I've come across here:

https://github.com/ericallam/supabase-realtime-js-esbuild

Please refer to the README for reproduction steps.

## Expected behavior

The types should resolve correctly in Node16/NodeNext, and the module resolution should as well.

## System information

- OS: macOS
- Version of supabase-js: 2.45.3
- Version of realtime-js: 2.10.5
- Version of Node.js: [e.g. 22.3.0]

## Additional context

We discovered these issues from user reports in Trigger.dev, as we use esbuild and have a new build system coming out shortly that outputs ESM.

**Comment by ericallam** [comment]
I've just updated the reproduction repo with how most of the module resolution problems go away if `"type": "module"` is removed from the `package.json`.

**Comment by ericallam** [comment]
It does look like this was recently added here: https://github.com/supabase/realtime-js/commit/95ab09e47ed7732eb21ac31eac743704bacc29aa

**Comment by filipecabaco** [comment]
change merged and fix released. thank you for reporting it 🙏
