### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime-js#46]
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

This library is currently plain JS, but we'd love it to be TypeScript

## Details

We just went through the exercise of converting [postgrest-js](https://github.com/supabase/postgrest-js) and [gotrue-js](https://github.com/supabase/gotrue-js) to TypeScript. This involves:

- Moving the build process over to the TypeScript compiler
- Adding types to all of the classes and methods
- [Optional] Migrating the tests over to Jest.

**Comment by abraaoduarte** [comment]
Can I work on this?

**Comment by kiwicopple** [comment]
Definitely @abraaoduarte - let me know if you need help

**Comment by abraaoduarte** [comment]
Ok, thanks.
I will open a PR for each file that I manage to pass to Typescript so I don't have too much to review at once.

**Comment by kiwicopple** [comment]
Hey @abraaoduarte checking in on this. How is everything going? I will be releasing another version of supabase-js soon and I'm planning to add the Typescript changes here. If you haven't started this already, let me know and I will pick it up 👍
