### ISSUE TITLE
Confirmation of a socket connection

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime-js#52]
Picking up from @ToryByte's tweet: https://twitter.com/ToryByte/status/1267225319947280385

Is there a way to wait for a subscription to connect? I cant find a way to wait for a subscription to be ready before I start running other statements. It would be nice if `subscribe()` returned a promise.

**Comment by w3b6x9** [comment]
This can be accomplished now depending on which version of `realtime-js` you're using. 

If you're using `realtime-js` `master`/`v1` then you can do:

```js
 const mySubscription = supabase
  .from('*')
  .on('*', payload => {
    console.log('Change received!', payload)
  })
  .subscribe()
  .receive('ok', () => console.log('Subscribed successfully so do something'))
```

If you're using `realtime-js` `rc`/`v2` then you can do:

```js
 const myChannel = supabase
  .channel('any')
  .on('postgres_changes', { event: '*', schema: 'public' }, payload => {
    console.log('Change received!', payload)
  })
  .subscribe(status => {
    if (status === 'SUBSCRIBED') {
       console.log('Subscribed successfully so do something')
    }
  })
```
