### ISSUE TITLE
The client reconnects during long-time receiving frequent messages.

### ISSUE THREAD

**Issue by abc3** [supabase/realtime-js#77]
# Bug report

## Describe the bug

If the server pushes many messages, for example, if DB has inserted 100k rows, the client will reconnect after ~40-120 sec.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Launch http://localhost:3000/stress
2. Open browser DevTools
3. Execute 100000
2. Wait for a little for the new message `Connecting` in the console

## Expected behavior

The client doesn't disconnect while receiving messages.

## Screenshots
<img width="1278" alt="Screenshot 2021-02-18 at 12 34 39" src="https://user-images.githubusercontent.com/1172600/108344331-ae42e080-71e5-11eb-96ce-22f09ba1c98b.png">

## System information

- OS: macOS Big Sur
- Browser: Google Chrome 88.0.4324.150 (Official Build) (x86_64)
- Version of supabase-js: 1.0.6
- Version of Node.js: v12.16.1

## Additional context

I suppose this is because the client can't receive a response to the heartbeat message. Server process too busy because of a lot of messages in the message box.

The solution can be to reset the `heartbeatTimer` on receiving any message.  If we've just gotten the message, everything is ok with the server connection, and heartbeat is unnecessary, right?

**Comment by w3b6x9** [comment]
@abc yep, I saw this while doing my tests for [RAM explosion on huge # of inserts #125](https://github.com/supabase/realtime/issues/125) issue b/c I was also doing 100k inserts. Thanks for reporting this! Let me take a look.

**Comment by w3b6x9** [comment]
@abc3 apologies for not tackling this issue sooner!

Let me know what you think of PR #80.
