### ISSUE TITLE
Socket connection gets terminated if heartbeat is not sent for 1 minute

### ISSUE THREAD

**Issue by DexterHuang** [supabase/realtime-js#94]
# Bug report
   Hi, I am dexter, I am here to report an issue where my client does not send a heartbeat for more than 1 minute.
After taking a brief look at the RealtimeClient source code, I have found this block here
https://github.com/supabase/realtime-js/blob/d463118b8758456cc2a37c5eef87d0bcaa14edf5/src/RealtimeClient.ts#L270-L274

In my case server always sends `"ref": null` so `_resetHeartbeat()` is always called whenever there is an incoming message.
because of this, the heartbeat is never sent as long as there are incoming messages which are almost always in my case.
I understand the intention was that if the message is received the alive time for the socket can be extended, but it seems like the server will disconnect if no heartbeat is sent, regardless of if there are any downstream messages or not.

I have temporatly patched my app to call ` sub.socket.push({ "topic": "phoenix", "event": "heartbeat", "payload": {}, ref: sub.socket.makeRef() });` every 50 seconds to ensure client does not disconnect and reconnects every time. and this does keep the connection alive. previously it disconnects every 1.0 minute

I hope this info can help you guys fix the bug :) the most naive way I can think of is just removing the `_resetHeartbeat()` call haha.

**Comment by DexterHuang** [comment]
@w3b6x9 @inian reference to our email previously :)

**Comment by w3b6x9** [comment]
@DexterHuang Thanks for creating this issue!

> https://github.com/supabase/realtime-js/blob/d463118b8758456cc2a37c5eef87d0bcaa14edf5/src/RealtimeClient.ts#L270-L274

This was actually released a week ago (see [here](https://github.com/supabase/realtime-js/releases/tag/v1.0.10)) and was apart of `supabase-js` [v1.18.1](https://github.com/supabase/supabase-js/releases/tag/v1.18.1) release. I think you version bumped to v1.18.0 so this isn't the issue.

I've been doing more investigating and this issue is more longstanding. It has to do with our heartbeat send logic. I'm currently working on a fix and will provide an update here when it's completed.

> I have temporatly patched my app to call sub.socket.push({ "topic": "phoenix", "event": "heartbeat", "payload": {}, ref: sub.socket.makeRef() });

Nice one!

**Comment by DexterHuang** [comment]
Ah understand 👍👍 thank you guys!

**Comment by w3b6x9** [comment]
@DexterHuang are you still experiencing this issue? i think this might have been taken care of with one of the latest supabase-js releases.

**Comment by DexterHuang** [comment]
@w3b6x9  Hi, yes, I have tested with `"@supabase/supabase-js": "^1.28.0"` just now, the issue is still there.
since last time until now, I have been using the workaround patch I mentioned in my app.

is this issue reproducible or its only me?

**Comment by w3b6x9** [comment]
@DexterHuang can you try `supabase-js` v1.29.1?

**Comment by DexterHuang** [comment]
@w3b6x9  tested with `1.29.1` still with the same issue

**Comment by w3b6x9** [comment]
@DexterHuang i just released a potential fix for this. can you please give `supabase-js` v1.30.4 a try?
